package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/skillrig/cli/pkg/skillcore"
)

// defaultIndexOut is the catalog's default destination: index.json at the origin
// repo root (contract index.md).
const defaultIndexOut = "index.json"

// indexCmd holds the index command's flags and its injectable cwd seam.
type indexCmd struct {
	opts *globalOpts
	out  string

	// getwd returns the working directory. Defaults to os.Getwd.
	getwd func() (string, error)
}

// newIndexCmd builds the `skillrig index` command (origin-side generator): run
// inside an origin repo, it regenerates the origin's catalog (index.json) from
// each skill's SKILL.md frontmatter so search has an honest, up-to-date catalog.
// It is not a consumer command — it writes the origin's own discovery artifact —
// and is deterministic: regenerating over an unchanged skill set is byte-identical.
func newIndexCmd(opts *globalOpts) *cobra.Command {
	ic := &indexCmd{
		opts:  opts,
		getwd: osGetwd,
	}

	cmd := &cobra.Command{
		Use:   "index",
		Short: "Regenerate the origin's catalog (index.json) from its skills' frontmatter",
		Long: "index regenerates the ORIGIN's machine-readable catalog (index.json) by walking\n" +
			"the origin's skills directory and parsing each skill's SKILL.md frontmatter — the\n" +
			"same parser add and verify use. Run it INSIDE the origin repo (locally or in CI on\n" +
			"merge): it is an origin-maintainer command, not a consumer command, and writes the\n" +
			"origin's own discovery artifact that search later reads.\n\n" +
			"It is a single-tip, full regeneration — the catalog is overwritten wholesale, sorted\n" +
			"by name with a stable key order and a trailing newline, so regenerating over an\n" +
			"unchanged skill set is byte-identical. The skillrigConvention and origin are read\n" +
			"from the origin's .skillrig-origin.toml (never hardcoded), so producer and consumer\n" +
			"share one source of truth.\n\n" +
			"Exit 0 on a written (or unchanged) catalog; exit 1 outside an origin repo, on an\n" +
			"unreadable skills directory, or on a malformed SKILL.md frontmatter.",
		Example: "  # Regenerate index.json at the origin repo root\n" +
			"  skillrig index\n\n" +
			"  # Write the catalog to an explicit path\n" +
			"  skillrig index --out catalog/index.json\n\n" +
			"  # Machine-readable summary of what was generated\n" +
			"  skillrig index --json",
		// Custom validator (not cobra.NoArgs) so an extra positional yields
		// what/why/fix instead of cobra's "unknown command" dead end (cli.md P1/P2).
		Args: func(_ *cobra.Command, args []string) error {
			if len(args) != 0 {
				return usageIndexArgs(args)
			}

			return nil
		},
		RunE: func(cmd *cobra.Command, _ []string) error {
			return ic.run(cmd)
		},
	}

	cmd.Flags().StringVar(&ic.out, "out", defaultIndexOut, "path to write the catalog to (default: index.json at the origin root)")

	return cmd
}

// run locates the origin repo root, regenerates the catalog from frontmatter via
// skillcore.GenerateCatalog (the one catalog generator, AP-04), writes it to the
// resolved --out path, and renders the summary. skillcore's failures are mapped
// to navigational *UsageError values (exit 1), preserving the raw cause for
// --verbose.
func (ic *indexCmd) run(cmd *cobra.Command) error {
	cwd, err := ic.getwd()
	if err != nil {
		return &UsageError{Msg: "cannot determine working directory\nwhy: " + err.Error(), Cause: err}
	}

	originRoot, err := gitToplevel(cmd.Context(), cwd)
	if err != nil {
		return usageIndexNotInOrigin(err)
	}

	data, err := skillcore.GenerateCatalog(originRoot)
	if err != nil {
		return mapIndexError(err)
	}

	// Parse the generated bytes back with the shared parser (AP-04) for the
	// summary's skill count and convention — the same numbers a consumer would
	// read, never recomputed from a parallel walk.
	catalog, err := skillcore.ParseCatalog(data)
	if err != nil {
		return mapIndexError(err)
	}

	outPath := ic.out
	if !filepath.IsAbs(outPath) {
		outPath = filepath.Join(originRoot, outPath)
	}

	if err := os.WriteFile(outPath, data, 0o644); err != nil { //nolint:gosec // G306: index.json is a committed, world-readable catalog artifact.
		return &UsageError{
			Msg: fmt.Sprintf("cannot write the catalog to %q\n", outPath) +
				"why: " + err.Error() + "\n" +
				"fix: check the path is writable, or pass --out to a different location",
			Cause: err,
		}
	}

	return renderIndexResult(cmd.OutOrStdout(), indexResult{
		Out:        outPath,
		Skills:     len(catalog.Skills),
		Convention: catalog.SkillrigConvention,
	}, ic.opts.json)
}

// usageIndexArgs builds the navigational usage error when index is given
// positional arguments it does not take (errors-as-navigation: what / why / fix).
func usageIndexArgs(args []string) *UsageError {
	return usageErrorf("index takes no arguments\n"+
		"why: it regenerates the whole origin catalog (got: %v)\n"+
		"fix: run skillrig index (add --out <path> to choose where to write)", args)
}

// usageIndexNotInOrigin builds the "not in an origin repo" usage error (exit 1):
// index must run inside the origin repository to find its .skillrig-origin.toml
// and skills directory.
func usageIndexNotInOrigin(cause error) *UsageError {
	return &UsageError{
		Msg: "not in an origin repository\n" +
			"why: index regenerates the origin's catalog and needs the origin repo (its .skillrig-origin.toml and skills/)\n" +
			"fix: run skillrig index inside the origin repo checkout",
		Cause: cause,
	}
}

// mapIndexError maps skillcore.GenerateCatalog's failures to navigational
// *UsageError values (exit 1): a missing/unreadable origin config or skills
// directory means this is not an origin repo; anything else (a malformed
// SKILL.md frontmatter) names the offending file via the wrapped cause. The raw
// cause is preserved for --verbose.
func mapIndexError(err error) error {
	if errors.Is(err, os.ErrNotExist) {
		return usageIndexNotInOrigin(err)
	}

	return &UsageError{
		Msg: "cannot generate the catalog\n" +
			"why: " + err.Error() + "\n" +
			"fix: check the named SKILL.md frontmatter, the origin's .skillrig-origin.toml, and the skills directory",
		Cause: err,
	}
}
